# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tanju's io
tagline:          'Make yo self before you wreck yo self'
description:      'A centralized location for summary and details of my making adventures beyond the ultraworld. Made by <a href="https://twitter.com/tanjub" target="_blank">@tanjuB</a>.'
#url:              http://hyde.getpoole.com
#baseurl:          /

author:
  name:           'Tanju Bayramoglu'
  url:            https://twitter.com/tanjub

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
